### ISSUE TITLE
sequence item 0: expected str instance, spacy.tokens.token.Token found

### ISSUE THREAD

**Issue by kafkaphoenix** [UtilityHotbar/rpgtools#1]
It seems something related with a wrong type
```
Attempting to translate: !  
Is punctuation, skipped     
Attempting to translate: +26
Making new word
Raw translation result: rhaeazhah
Traceback (most recent call last):
  File "C:\Users\sorak\Documents\GitHub\civsim_play\Scripts\civsim-run-script.py", line 33, in <module>
    sys.exit(load_entry_point('civsim', 'console_scripts', 'civsim-run')())
  File "c:\users\sorak\documents\github\civsim\civsim\scripts\run.py", line 22, in main
    gm.hourglass()
  File "c:\users\sorak\documents\github\civsim\civsim\game_master.py", line 69, in hourglass
    self._adam(roll('1d6'), world)
  File "c:\users\sorak\documents\github\civsim\civsim\game_master.py", line 60, in _adam
    Civilisation.born_civ(lat, long, world)
  File "c:\users\sorak\documents\github\civsim\civsim\civ\civ.py", line 68, in born_civ
    sprout = cls(f'{cls.civ_emblems[cls.civ_ptr]}+{cls.civ_ptr}', cls.civ_emblems[cls.civ_ptr], [lat, long], world, parent, cpu)
  File "c:\users\sorak\documents\github\civsim\civsim\civ\civ.py", line 29, in __init__
    self._name = self._language.brute_force_translate(name)
  File "c:\users\sorak\documents\github\civsim\civsim\third\rpgtools\lang_gen.py", line 140, in brute_force_translate
    new_phrase.append(self.get_word(word))
  File "c:\users\sorak\documents\github\civsim\civsim\third\rpgtools\lang_gen.py", line 77, in get_word
    return ' '.join(finished_word)
TypeError: sequence item 0: expected str instance, spacy.tokens.token.Token found
```

**Comment by kafkaphoenix** [comment]
@UtilityHotbar The game crash because get_word is skipping punctuation marks and adding the token without doing str() first. Then next iteration happens and try to return a list with a token and a string crashing the program
![image](https://user-images.githubusercontent.com/17835242/118538553-a21be000-b74e-11eb-900d-a0e531c9a863.png)

**Comment by UtilityHotbar** [comment]
Should be fixed now
